/**
 * API Library - scripts/seedMassiveApis.js
 * Massive Seeder: Expands catalogue to 100+ verified APIs across all 12 categories
 */

import fs from "fs";
import { DEMO_APIS as INITIAL_APIS } from "../js/demoData.js";

const PROJECT_ID = "apilib-f706f";

export const ADDITIONAL_APIS = [
  // ==========================================
  // 1. AI (Искусственный интеллект) +8
  // ==========================================
  {
    id: "cohere-api",
    name: "Cohere API",
    category: "AI",
    shortDescription: "Корпоративные модели генерации текста, суммаризации и мультиязычного ранжирования (Rerank).",
    description: "Cohere специализируется на Enterprise AI решениях. API предоставляет высокоэффективные модели для генерации текста (Command R+), семантического поиска и Rerank — лучшего в индустрии инструмента для улучшения качества выдачи RAG-систем.",
    tags: ["ai", "cohere", "rerank", "embeddings", "rag"],
    logo: "CO",
    websiteUrl: "https://cohere.com",
    documentationUrl: "https://docs.cohere.com",
    githubUrl: "https://github.com/cohere-ai",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "1,000 requests/month (Free Trial)",
    rating: 4.8,
    ratingCount: 165,
    popularity: 1320,
    status: "active",
    features: ["Модели Command R и Command R+", "Индустриальный стандарт Rerank для RAG", "Мультиязычные эмбеддинги 100+ языков", "Приватные корпоративные развертывания"]
  },
  {
    id: "replicate-api",
    name: "Replicate API",
    category: "AI",
    shortDescription: "Запуск тысяч моделей машинного обучения с открытым исходным кодом одной строкой кода в облаке.",
    description: "Replicate превращает любые open-source модели в масштабируемые бессерверные API. Поддерживает запуск Stable Diffusion XL, Flux, Llama 3, Whisper, кодеков улучшения качества видео и апскейлеров изображений.",
    tags: ["ai", "replicate", "flux", "diffusion", "serverless"],
    logo: "RE",
    websiteUrl: "https://replicate.com",
    documentationUrl: "https://replicate.com/docs",
    githubUrl: "https://github.com/replicate/replicate-javascript",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "По квотам учетной записи",
    rating: 4.8,
    ratingCount: 240,
    popularity: 1850,
    status: "active",
    features: ["Запуск моделей Flux, SDXL, Llama", "Оплата посекундно за вычислительное время", "Вебхуки на завершение генераций", "Автоматический scale-to-zero"]
  },
  {
    id: "mistral-ai-api",
    name: "Mistral AI API",
    category: "AI",
    shortDescription: "Открытые европейские языковые модели Mistral Large, Codestral и NeMo с высокой плотностью рассуждений.",
    description: "Mistral AI предоставляет доступ к флагманским компактным и крупным моделям. Codestral оптимизирован для автодополнения кода в IDE, а Mistral Large конкурирует с ведущими проприетарными решениями по логике и аналитике.",
    tags: ["ai", "mistral", "codestral", "llm", "europe"],
    logo: "MA",
    websiteUrl: "https://mistral.ai",
    documentationUrl: "https://docs.mistral.ai",
    githubUrl: "https://github.com/mistralai/client-ts",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Бесплатный уровень с лимитами",
    rating: 4.8,
    ratingCount: 195,
    popularity: 1720,
    status: "active",
    features: ["Codestral — специализированная модель для программирования", "Поддержка FIM (Fill-in-the-Middle)", "Function Calling и Structured Output", "Строгое соответствие GDPR"]
  },
  {
    id: "groq-api",
    name: "Groq Cloud API",
    category: "AI",
    shortDescription: "Сверхскоростной инференс LLM на процессорах LPU со скоростью до 800+ токенов в секунду.",
    description: "Groq разработал инновационный процессор LPU (Language Processing Unit), обеспечивающий генерацию ответов с задержкой в доли секунды. Поддерживает запуск Llama 3.1, Mixtral и Whisper практически со скоростью мысли.",
    tags: ["ai", "groq", "lpu", "fast", "llama3"],
    logo: "GC",
    websiteUrl: "https://groq.com",
    documentationUrl: "https://console.groq.com/docs/quickstart",
    githubUrl: "https://github.com/groq",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "30 RPM (Free Tier)",
    rating: 4.9,
    ratingCount: 310,
    popularity: 2400,
    status: "active",
    features: ["Скорость генерации более 800 токенов/сек", "Полная совместимость с OpenAI SDK", "Модели Llama 3.3 70B и Whisper-large", "Сверхнизкое энергопотребление LPU"]
  },
  {
    id: "stability-ai-api",
    name: "Stability AI API",
    category: "AI",
    shortDescription: "Генерация изображений, 3D-объектов, видео и редактирование фотографий через Stable Diffusion.",
    description: "Stability AI API открывает доступ к семейству моделей Stable Diffusion 3.5, Stable Video Diffusion и Stable Fast 3D. Позволяет создавать иллюстрации, расширять границы изображений (Outpainting), удалять фон и анимировать кадры.",
    tags: ["ai", "images", "diffusion", "stable-diffusion", "art"],
    logo: "SA",
    websiteUrl: "https://stability.ai",
    documentationUrl: "https://platform.stability.ai/docs/api-reference",
    githubUrl: "https://github.com/Stability-AI",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Стартовые бесплатные кредиты",
    rating: 4.7,
    ratingCount: 180,
    popularity: 1540,
    status: "active",
    features: ["Stable Diffusion 3.5 Large и Turbo", "Генерация коротких видеороликов из фото", "Inpainting и удаление лишних объектов", "Создание 3D-ассетов для игр"]
  },
  {
    id: "deepl-api",
    name: "DeepL Translation API",
    category: "AI",
    shortDescription: "Самый точный и естественный нейросетевой перевод текстов и документов на 30+ языков.",
    description: "DeepL API считается золотым стандартом машинного перевода благодаря способности улавливать тончайшие языковые нюансы и контекст. Поддерживает перевод текстовых фрагментов, HTML/XML-разметки и файлов Word, PDF, PowerPoint целиком.",
    tags: ["ai", "translation", "languages", "nlp", "deepl"],
    logo: "DT",
    websiteUrl: "https://www.deepl.com",
    documentationUrl: "https://www.deepl.com/docs-api",
    githubUrl: "https://github.com/DeepLcom",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "500,000 символов/мес (Free)",
    rating: 4.9,
    ratingCount: 290,
    popularity: 2100,
    status: "active",
    features: ["Перевод с сохранением структуры тегов HTML", "Пакетный перевод документов PDF и DOCX", "Пользовательские словари и глоссарии", "Настройка формального/неформального тона"]
  },
  {
    id: "pinecone-api",
    name: "Pinecone Vector Database API",
    category: "AI",
    shortDescription: "Бессерверная векторная база данных для семантического поиска и RAG-приложений на миллионы эмбеддингов.",
    description: "Pinecone предоставляет серверлес-инфраструктуру для хранения и сверхбыстрого векторного поиска по схожести (cosine, euclidean, dotproduct). Легко масштабируется от сотен векторов до миллиардов без необходимости управления инфраструктурой.",
    tags: ["ai", "vector", "database", "embeddings", "rag"],
    logo: "PV",
    websiteUrl: "https://www.pinecone.io",
    documentationUrl: "https://docs.pinecone.io",
    githubUrl: "https://github.com/pinecone-io",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Бесплатный индекс Starter",
    rating: 4.8,
    ratingCount: 230,
    popularity: 1680,
    status: "active",
    features: ["Серверлес-векторные индексы с автоскейлингом", "Поиск схожести с задержкой до 50 мс", "Фильтрация по метаданным векторов", "Официальные SDK для Python, JS, Go"]
  },
  {
    id: "assemblyai-api",
    name: "AssemblyAI Speech AI",
    category: "AI",
    shortDescription: "Распознавание речи (Speech-to-Text), разделение по спикерам и анализ аудиозаписей.",
    description: "AssemblyAI преобразует речь в текст с высочайшей точностью. Включает автоматическое определение говорящих (Speaker Diarization), цензурирование ненормативной лексики, анализ тональности и создание кратких выжимок разговоров.",
    tags: ["ai", "speech", "transcription", "audio", "stt"],
    logo: "AS",
    websiteUrl: "https://www.assemblyai.com",
    documentationUrl: "https://www.assemblyai.com/docs",
    githubUrl: "https://github.com/AssemblyAI/assemblyai-node-sdk",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Бесплатные стартовые часы аудио",
    rating: 4.7,
    ratingCount: 155,
    popularity: 1210,
    status: "active",
    features: ["Транскрипция аудиофайлов и прямых эфиров", "Разделение спикеров в диалоге", "Автоматические таймкоды для каждого слова", "Поиск ключевых тем и суммаризация встречи"]
  },

  // ==========================================
  // 2. WEATHER (Погода и климат) +6
  // ==========================================
  {
    id: "open-meteo-api",
    name: "Open-Meteo Weather API",
    category: "Weather",
    shortDescription: "Полностью открытый и бесплатный API погоды на основе моделей национальных метеослужб (NOAA, DWD, ECMWF).",
    description: "Open-Meteo агрегирует прогнозы ведущих мировых метеорологических агентств (GFS, ECMWF, ICON). Предоставляет детальные прогнозы почасовой температуры, ветра, влажности, солнечной радиации и осадков без обязательных API-ключей.",
    tags: ["weather", "opensource", "forecast", "free", "solar"],
    logo: "OW",
    websiteUrl: "https://open-meteo.com",
    documentationUrl: "https://open-meteo.com/en/docs",
    githubUrl: "https://github.com/open-meteo/open-meteo",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "10,000 запросов/день (Free)",
    rating: 4.9,
    ratingCount: 340,
    popularity: 2200,
    status: "active",
    features: ["100% открытые исходные коды и данные", "Не требует регистрации и ключей API", "Высокое разрешение до 1 км", "Данные солнечной и ветровой энергии"]
  },
  {
    id: "accuweather-api",
    name: "AccuWeather API",
    category: "Weather",
    shortDescription: "Премиальные метеорологические прогнозы, радарные карты и фирменный индекс RealFeel Temperature.",
    description: "AccuWeather предоставляет проверенные десятилетиями прогнозы погоды для миллионов локаций. API славится индексом ощущаемой температуры RealFeel, детализацией сезонных аллергенов и оповещениями о суровых штормах.",
    tags: ["weather", "accuweather", "forecast", "radar", "realfeel"],
    logo: "AC",
    websiteUrl: "https://developer.accuweather.com",
    documentationUrl: "https://developer.accuweather.com/apis",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "50 requests/day (Free Trial)",
    rating: 4.6,
    ratingCount: 160,
    popularity: 1400,
    status: "active",
    features: ["Запатентованный индекс RealFeel", "Почасовые прогнозы на 120 часов", "Спутниковые и радарные тайлы", "Предупреждения о стихийных бедствиях"]
  },
  {
    id: "visual-crossing-weather",
    name: "Visual Crossing Weather API",
    category: "Weather",
    shortDescription: "Глобальные архивы исторической погоды за 50+ лет и высокоточные текущие прогнозы.",
    description: "Visual Crossing — один из лучших источников исторических данных о погоде. Позволяет запрашивать погоду в любой точке мира на любую дату с 1970 года, а также 15-дневные прогнозные модели.",
    tags: ["weather", "history", "archive", "climate", "analytics"],
    logo: "VC",
    websiteUrl: "https://www.visualcrossing.com",
    documentationUrl: "https://www.visualcrossing.com/resources/documentation/weather-api/timeline-weather-api/",
    githubUrl: "https://github.com/visualcrossing",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "1,000 запросов/день (Free)",
    rating: 4.7,
    ratingCount: 130,
    popularity: 980,
    status: "active",
    features: ["Исторические данные погоды с 1970 года", "Единый Timeline API для прошлого и будущего", "Аналитика степени инсоляции и влажности", "Экспорт в CSV и JSON"]
  },
  {
    id: "airvisual-api",
    name: "IQAir AirVisual API",
    category: "Weather",
    shortDescription: "Глобальный мониторинг качества воздуха (AQI), концентрации PM2.5 и загрязнения атмосферы.",
    description: "IQAir AirVisual API предоставляет данные индекса качества воздуха (AQI), концентрации частиц PM2.5, PM10, озона, оксида азота и серы. Позволяет отображать карту загрязнений и рекомендации по здоровью для жителей мегаполисов.",
    tags: ["weather", "airquality", "aqi", "pollution", "health"],
    logo: "IA",
    websiteUrl: "https://www.iqair.com",
    documentationUrl: "https://www.iqair.com/air-pollution-data-api",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "10,000 requests/month (Community)",
    rating: 4.8,
    ratingCount: 145,
    popularity: 1150,
    status: "active",
    features: ["Глобальный расчет индекса AQI США и Китая", "Концентрация опасных микрочастиц PM2.5", "Связка погоды и загрязнения воздуха", "Данные с 80 000+ станций мониторинга"]
  },
  {
    id: "stormglass-marine-api",
    name: "Storm Glass Marine API",
    category: "Weather",
    shortDescription: "Морская погода для серфинга, мореплавания и рыбалки: волны, приливы, течения и ветер.",
    description: "Storm Glass API агрегирует данные ведущих гидрометеорологических институтов мира для предоставления исчерпывающей информации об океанах: высота и направление волн, периоды зыби, карта приливов и отливов, температура морской воды.",
    tags: ["weather", "marine", "ocean", "surf", "waves"],
    logo: "SG",
    websiteUrl: "https://stormglass.io",
    documentationUrl: "https://docs.stormglass.io",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "10 requests/day (Free)",
    rating: 4.6,
    ratingCount: 95,
    popularity: 760,
    status: "active",
    features: ["Высота, направление и период морских волн", "Астрономические прогнозы приливов и отливов", "Скорость и температура океанических течений", "Идеальный инструмент для приложений серфинга"]
  },
  {
    id: "meteo-concept-api",
    name: "Météo-Concept API",
    category: "Weather",
    shortDescription: "Европейские метеорологические данные, прогнозы вероятности дождя и ветра.",
    description: "API поставляет детализированные прогнозы европейских метеорологических служб с поминутной детализацией вероятности осадков и карт порывов ветра.",
    tags: ["weather", "europe", "wind", "rain", "forecast"],
    logo: "MT",
    websiteUrl: "https://api.meteo-concept.com",
    documentationUrl: "https://api.meteo-concept.com/documentation",
    githubUrl: "https://github.com",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "10,000 calls/month",
    rating: 4.5,
    ratingCount: 75,
    popularity: 610,
    status: "active",
    features: ["Поминутная вероятность дождя", "Радарные наблюдения штормов", "Географическая привязка по коммунам", "Формат JSON"]
  },

  // ==========================================
  // 3. MAPS & GEOLOCATION +6
  // ==========================================
  {
    id: "here-technologies-api",
    name: "HERE Technologies Maps",
    category: "Maps",
    shortDescription: "Премиальные автомобильные карты, матрица маршрутизации для грузовиков и геокодирование.",
    description: "HERE Technologies — ключевой поставщик карт для автоконцернов (Audi, BMW, Mercedes). API включает поддержку специфических грузовых ограничений (высота мостов, опасные грузы), геозоны (Geofencing) и точнейшую оценку пробок.",
    tags: ["maps", "here", "automotive", "routing", "logistics"],
    logo: "HT",
    websiteUrl: "https://developer.here.com",
    documentationUrl: "https://www.here.com/docs/",
    githubUrl: "https://github.com/heremaps",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "250,000 транзакций/мес (Free)",
    rating: 4.8,
    ratingCount: 210,
    popularity: 1580,
    status: "active",
    features: ["Специализированная маршрутизация грузовиков", "250 000 бесплатных вызовов каждый месяц", "Построение изолиний времени пути", "Точнейшие данные о дорожных знаках и знаках скорости"]
  },
  {
    id: "geoapify-api",
    name: "Geoapify Location Platform",
    category: "Maps",
    shortDescription: "Современный API геокодирования, автокомплита адресов, изохрон и поиска мест (POI).",
    description: "Geoapify объединяет открытые данные OpenStreetMap с коммерческими источниками для предоставления быстрого автокомплита адресов, генерации статических карт, расчета матриц маршрутов и оптимизации пути для нескольких курьеров.",
    tags: ["maps", "geoapify", "geocoding", "autocomplete", "isochrones"],
    logo: "GL",
    websiteUrl: "https://www.geoapify.com",
    documentationUrl: "https://apidocs.geoapify.com",
    githubUrl: "https://github.com/geoapify",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "3,000 запросов/день (Free)",
    rating: 4.7,
    ratingCount: 150,
    popularity: 1220,
    status: "active",
    features: ["Умный адресный автокомплит для форм ввода", "Расчет зон досягаемости (Isochrones)", "Оптимизация маршрутов для нескольких точек", "Генерация статических карт в PNG"]
  },
  {
    id: "ip-api-com",
    name: "IP-API Geolocation",
    category: "Maps",
    shortDescription: "Мгновенное определение страны, города, провайдера и координат пользователя по его IP-адресу.",
    description: "IP-API — самый быстрый и простой способ определить местоположение пользователя без запроса разрешения на геолокацию в браузере. Возвращает страну, город, почтовый индекс, широту/долготу, часовой пояс и данные интернет-провайдера (ISP/ASN).",
    tags: ["maps", "ip", "geolocation", "network", "free"],
    logo: "IG",
    websiteUrl: "https://ip-api.com",
    documentationUrl: "https://ip-api.com/docs",
    githubUrl: "https://github.com",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "45 запросов/мин (Free)",
    rating: 4.8,
    ratingCount: 310,
    popularity: 2600,
    status: "active",
    features: ["Работает без API ключей на бесплатном тарифе", "Задержка ответа серверов менее 20 мс", "Автоматическая локализация языков сайтов", "Определение мобильных сетей и провайдеров"]
  },
  {
    id: "tomtom-maps-api",
    name: "TomTom Maps API",
    category: "Maps",
    shortDescription: "Интеллектуальная маршрутизация для электромобилей, данные о пробках и поисковой движок.",
    description: "TomTom — один из старейших лидеров мировой навигации. API выделяется специализированными маршрутами для электромобилей (учет расхода батареи и станций зарядки) и детальной историей дорожных заторов.",
    tags: ["maps", "tomtom", "ev", "traffic", "navigation"],
    logo: "TM",
    websiteUrl: "https://developer.tomtom.com",
    documentationUrl: "https://developer.tomtom.com/documentation",
    githubUrl: "https://github.com/tomtom-international",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "2,500 requests/day (Free)",
    rating: 4.6,
    ratingCount: 140,
    popularity: 1140,
    status: "active",
    features: ["Оптимизация маршрутов с зарядками для EV", "Высокая точность прогноза времени прибытия (ETA)", "Векторные тайлы для веб-приложений", "Уведомления о перекрытиях дорог"]
  },
  {
    id: "locationiq-api",
    name: "LocationIQ",
    category: "Maps",
    shortDescription: "Доступный масштабируемый сервис прямого и обратного геокодирования и статических карт.",
    description: "LocationIQ берет данные OpenStreetMap и предоставляет сверхбыстрый отказоустойчивый API с SLA 99.99%. Отличное бюджетное решение для высоконагруженных проектов.",
    tags: ["maps", "geocoding", "locationiq", "tiles", "staticmaps"],
    logo: "LO",
    websiteUrl: "https://locationiq.com",
    documentationUrl: "https://docs.locationiq.com",
    githubUrl: "https://github.com/location-iq",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "5,000 requests/day (Free)",
    rating: 4.7,
    ratingCount: 125,
    popularity: 1050,
    status: "active",
    features: ["5 000 бесплатных запросов каждый день", "Автокомплит поисковой строки адреса", "Генерация статических превью карт", "Поддержка работы без кредитной карты"]
  },
  {
    id: "graphhopper-routing-api",
    name: "GraphHopper Routing Engine",
    category: "Maps",
    shortDescription: "Быстрый движок прокладки маршрутов для пешеходов, велосипедистов и автомобилей.",
    description: "GraphHopper славится невероятной скоростью расчетов маршрутов на графах дорог OpenStreetMap. Позволяет решать сложнейшие логистические задачи коммивояжера (VRP) для автопарков.",
    tags: ["maps", "routing", "graphs", "logistics", "vrp"],
    logo: "GR",
    websiteUrl: "https://www.graphhopper.com",
    documentationUrl: "https://docs.graphhopper.com",
    githubUrl: "https://github.com/graphhopper/graphhopper",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "500 requests/day (Free)",
    rating: 4.7,
    ratingCount: 110,
    popularity: 890,
    status: "active",
    features: ["Алгоритмы оптимизации логистики доставки VRP", "Профили маршрутов для велосипедов и трекинга", "Поддержка навигационных инструкций на 40+ языках", "Open-source ядро на Java"]
  },

  // ==========================================
  // 4. FINANCE (Финансы и платежи) +6
  // ==========================================
  {
    id: "coinmarketcap-api",
    name: "CoinMarketCap API",
    category: "Finance",
    shortDescription: "Профессиональные финансовые данные рынка криптовалют от ключевого агрегатора индустрии.",
    description: "CoinMarketCap API предоставляет доступ к проверенным институциональным данным о ценах криптовалют, объемах торгов на биржах, глобальных метриках доминирования Bitcoin, разводненной капитализации (FDV) и листингах новых токенов.",
    tags: ["finance", "crypto", "cmc", "marketcap", "bitcoin"],
    logo: "CO",
    websiteUrl: "https://coinmarketcap.com",
    documentationUrl: "https://coinmarketcap.com/api/documentation/v1/",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "10,000 call credits/мес (Free)",
    rating: 4.8,
    ratingCount: 320,
    popularity: 2600,
    status: "active",
    features: ["Индустриальный стандарт ранжирования токенов", "Данные о спотовых и деривативных биржах", "Глобальные индексы капитализации крипторынка", "API конвертации крипто-фиат"]
  },
  {
    id: "alpha-vantage-api",
    name: "Alpha Vantage Stock API",
    category: "Finance",
    shortDescription: "Биржевые котировки акций США (NYSE, NASDAQ), ETF, сырьевых товаров и 50+ технических индикаторов.",
    description: "Alpha Vantage поставляет котировки ценных бумаг в реальном времени и с историей за 20+ лет. Включает готовый расчет технических индикаторов (SMA, EMA, RSI, MACD, полосы Боллинджера) и фундаментальные данные отчетности компаний (P/E, балансы, прибыль).",
    tags: ["finance", "stocks", "nasdaq", "trading", "indicators"],
    logo: "AV",
    websiteUrl: "https://www.alphavantage.co",
    documentationUrl: "https://www.alphavantage.co/documentation/",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "25 requests/day (Free)",
    rating: 4.7,
    ratingCount: 280,
    popularity: 2150,
    status: "active",
    features: ["Исторические дневные, недельные и внутридневные свечи", "50+ готовых математических индикаторов трейдинга", "Фундаментальные финансовые показатели компаний", "Курсы сырья: нефть, золото, природный газ"]
  },
  {
    id: "polygon-io-api",
    name: "Polygon.io Market Data",
    category: "Finance",
    shortDescription: "Сверхскоростные рыночные данные бирж США по акциям, опционам, форексу и крипте.",
    description: "Polygon.io транслирует сырые биржевые тики и сделки напрямую от бирж NASDAQ и NYSE с задержкой в микросекунды. Идеален для алготрейдинга, финтех-платформ и торговых терминалов.",
    tags: ["finance", "trading", "stocks", "options", "realtime"],
    logo: "PM",
    websiteUrl: "https://polygon.io",
    documentationUrl: "https://polygon.io/docs",
    githubUrl: "https://github.com/polygon-io",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "5 requests/min (Free)",
    rating: 4.9,
    ratingCount: 210,
    popularity: 1870,
    status: "active",
    features: ["Прямые потоки сделок с бирж США", "Исторические свечи тикового уровня", "WebSockets для реалтайм котировок", "Опционные цепочки и греки"]
  },
  {
    id: "plaid-api",
    name: "Plaid Banking API",
    category: "Finance",
    shortDescription: "Безопасное подключение банковских счетов пользователей, просмотр балансов и истории транзакций.",
    description: "Plaid позволяет финансовым приложениям безопасно связываться с 12 000+ банками по всему миру. Пользователь авторизуется в своем банке, а приложение получает доступ к балансам, категоризированным транзакциям и проверке платежеспособности.",
    tags: ["finance", "banking", "openbanking", "transactions", "fintech"],
    logo: "PB",
    websiteUrl: "https://plaid.com",
    documentationUrl: "https://plaid.com/docs/",
    githubUrl: "https://github.com/plaid/plaid-node",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "100 подключений в Sandbox",
    rating: 4.8,
    ratingCount: 190,
    popularity: 1650,
    status: "active",
    features: ["Связка с 12 000+ банками мира", "Умная автоматическая категоризация расходов", "Проверка подлинности владельца счета", "Удобный UI-виджет Plaid Link"]
  },
  {
    id: "binance-public-api",
    name: "Binance Public API",
    category: "Finance",
    shortDescription: "Открытый доступ к биржевым стаканам (Order Book), сделкам и свечам крупнейшей криптобиржи.",
    description: "Binance предоставляет высоконагруженный публичный REST API для получения глубины рынка, тикеров цен в реальном времени и истории сделок по сотням торговых пар без необходимости создавать аккаунт и генерировать ключи.",
    tags: ["finance", "crypto", "binance", "trading", "orderbook"],
    logo: "BP",
    websiteUrl: "https://www.binance.com",
    documentationUrl: "https://binance-docs.github.io/apidocs/spot/en/",
    githubUrl: "https://github.com/binance",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "1,200 requests/min",
    rating: 4.7,
    ratingCount: 350,
    popularity: 2900,
    status: "active",
    features: ["Публичные данные без регистрации и API ключей", "Свечи (Klines) с интервалом от 1 секунды", "Книга заявок (Depth) в реальном времени", "Сверхвысокие лимиты запросов"]
  },
  {
    id: "paypal-developer-api",
    name: "PayPal REST API",
    category: "Finance",
    shortDescription: "Глобальный прием платежей через кошельки PayPal, дебетовые карты и рассрочку Pay Later.",
    description: "PayPal REST API позволяет внедрять оплату на сайтах по всему миру. Поддерживает PayPal Checkout, регулярные подписки, выплаты фрилансерам (Payouts) и верификацию споров о возвратах.",
    tags: ["finance", "paypal", "checkout", "ecommerce", "payments"],
    logo: "PA",
    websiteUrl: "https://developer.paypal.com",
    documentationUrl: "https://developer.paypal.com/api/rest/",
    githubUrl: "https://github.com/paypal",
    authentication: "OAuth 2.0",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Тестовая песочница без лимитов",
    rating: 4.6,
    ratingCount: 260,
    popularity: 2100,
    status: "active",
    features: ["Оплата в 200+ странах и 25 валютах", "Смарт-кнопки PayPal Checkout", "Программа защиты продавцов и покупателей", "Песочница с генерацией виртуальных счетов"]
  },

  // ==========================================
  // 5. GAMES (Игры и гейминг) +6
  // ==========================================
  {
    id: "steam-web-api",
    name: "Steam Web API",
    category: "Games",
    shortDescription: "Данные об играх Steam, профилях игроков, игровом инвентаре, достижениях и друзьях.",
    description: "Steam Web API от Valve позволяет приложениям взаимодействовать с экосистемой Steam: получать списки игр в библиотеке пользователя, статус нахождения в сети, достижения, инвентарь предметов CS2/Dota 2 и статистику онлайна игр.",
    tags: ["games", "steam", "valve", "cs2", "dota2"],
    logo: "SW",
    websiteUrl: "https://steamcommunity.com/dev",
    documentationUrl: "https://partner.steamgames.com/doc/webapi_overview",
    githubUrl: "https://github.com/ValveSoftware",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "100,000 requests/day",
    rating: 4.7,
    ratingCount: 390,
    popularity: 3100,
    status: "active",
    features: ["Статистика онлайна и списки игроков", "Достижения пользователя в играх", "Инвентарь предметов Steam Community", "Авторизация через Steam OpenID"]
  },
  {
    id: "chess-com-api",
    name: "Chess.com Public API",
    category: "Games",
    shortDescription: "Бесплатные открытые данные профилей шахматистов, рейтингов, архивов партий (PGN) и турниров.",
    description: "Официальный публичный API ведущей мировой шахматной платформы Chess.com. Позволяет загружать сыгранные партии гроссмейстеров и обычных игроков в формате PGN, текущие рейтинги в блиц/рапид/пулю и расписание турниров.",
    tags: ["games", "chess", "pgn", "ratings", "tournaments"],
    logo: "CP",
    websiteUrl: "https://www.chess.com",
    documentationUrl: "https://www.chess.com/news/view/published-data-api",
    githubUrl: "https://github.com",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Разумное использование без ключей",
    rating: 4.9,
    ratingCount: 220,
    popularity: 1840,
    status: "active",
    features: ["100% бесплатный без API ключей", "Скачивание архивов партий в формате PGN", "Рейтинги гроссмейстеров и статистика стримеров", "Просмотр партий текущих клубных матчей"]
  },
  {
    id: "riot-games-api",
    name: "Riot Games Developer API",
    category: "Games",
    shortDescription: "Статистика матчей, ранги игроков и история битв в League of Legends, Valorant и TFT.",
    description: "Официальный API компании Riot Games. Открывает доступ к данным о матчах League of Legends, рангах призывателей, мастерству чемпионов, истории турниров и событиям внутри матча в реальном времени.",
    tags: ["games", "riot", "lol", "valorant", "esports"],
    logo: "RG",
    websiteUrl: "https://developer.riotgames.com",
    documentationUrl: "https://developer.riotgames.com/apis",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "100 requests / 2 min (Dev Key)",
    rating: 4.8,
    ratingCount: 270,
    popularity: 2450,
    status: "active",
    features: ["Ранги и статистика игроков LoL и Valorant", "Таймлайны матчей и детальный урон по минутам", "Данные внутриигровых предметов и рун", "Активные игры в режиме реального времени"]
  },
  {
    id: "opentdb-api",
    name: "Open Trivia Database",
    category: "Games",
    shortDescription: "Открытая база данных викторин с тысячами вопросов различной сложности и категорий.",
    description: "Open Trivia DB предоставляет бесплатный RESTful API для создания игр-викторин. Содержит вопросы с множественным выбором или 'правда/ложь' по науке, истории, кино, видеоиграм, географии и спорту.",
    tags: ["games", "trivia", "quiz", "questions", "education"],
    logo: "OT",
    websiteUrl: "https://opentdb.com",
    documentationUrl: "https://opentdb.com/api_config.php",
    githubUrl: "https://github.com",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "1 запрос в 5 секунд",
    rating: 4.8,
    ratingCount: 190,
    popularity: 1450,
    status: "active",
    features: ["Тысячи проверенных вопросов", "Разбиение по 24 категориям знаний", "3 уровня сложности (Easy, Medium, Hard)", "Система токенов сессии против повторов"]
  },
  {
    id: "dnd5e-api",
    name: "D&D 5th Edition API",
    category: "Games",
    shortDescription: "Полный справочник правил настольной ролевой игры Dungeons & Dragons: заклинания, классы, монстры.",
    description: "Открытый справочник D&D 5e (SRD). Содержит структурированную информацию обо всех классах персонажей, расах, заклинаниях, монстрах с их характеристиками, оружии и магических предметах.",
    tags: ["games", "dnd", "rpg", "tabletop", "dragons"],
    logo: "D5",
    websiteUrl: "https://www.dnd5eapi.co",
    documentationUrl: "https://www.dnd5eapi.co/docs/",
    githubUrl: "https://github.com/5e-bits/5e-srd-api",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Свободный публичный доступ",
    rating: 4.9,
    ratingCount: 230,
    popularity: 1720,
    status: "active",
    features: ["Полный свод правил System Reference Document (SRD)", "Бестиарий монстров с очками здоровья и атак", "Каталог заклинаний по школам магии", "Поддержка GraphQL и REST интерфейсов"]
  },
  {
    id: "freetogame-api",
    name: "FreeToGame API",
    category: "Games",
    shortDescription: "Каталог лучших бесплатных игр для ПК и браузеров с фильтрацией по жанрам и графике.",
    description: "FreeToGame отслеживает все актуальные бесплатные MMO, шутеры, RPG и королевские битвы. Позволяет получать свежие обновления об играх, системных требованиях и прямых ссылках на скачивание.",
    tags: ["games", "f2p", "mmo", "freestuff", "pc"],
    logo: "FR",
    websiteUrl: "https://www.freetogame.com",
    documentationUrl: "https://www.freetogame.com/api-doc",
    githubUrl: "https://github.com",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Не ограничен",
    rating: 4.6,
    ratingCount: 140,
    popularity: 1180,
    status: "active",
    features: ["Каталог сотен F2P игр", "Скриншоты и системные требования", "Сортировка по популярности и новизне", "Не требует ключей и регистрации"]
  },

  // ==========================================
  // 6. MOVIES (Кино и сериалы) +6
  // ==========================================
  {
    id: "tvmaze-api",
    name: "TVMaze TV Shows API",
    category: "Movies",
    shortDescription: "Бесплатный REST API телесериалов, расписания выхода серий, актерских составов и кадров.",
    description: "TVMaze предоставляет исчерпывающую информацию о мировых телесериалах и шоу на стриминговых сервисах. Включает детальные графики выхода новых эпизодов, биографии актеров, галереи постеров и описания сезонов без необходимости API-ключа.",
    tags: ["movies", "tv", "series", "episodes", "schedule"],
    logo: "TT",
    websiteUrl: "https://www.tvmaze.com",
    documentationUrl: "https://www.tvmaze.com/api",
    githubUrl: "https://github.com",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "20 calls / 10 sec",
    rating: 4.8,
    ratingCount: 240,
    popularity: 1890,
    status: "active",
    features: ["100% бесплатный и доступный без токенов", "Точные даты выхода серий и сезонов", "Встроенный быстрый поиск с опечатками", "Галереи постеров и кадров высокого разрешения"]
  },
  {
    id: "anilist-api",
    name: "AniList Anime & Manga GraphQL API",
    category: "Movies",
    shortDescription: "Крупнейшая база данных аниме, манги, студий анимации и персонажей на базе современного GraphQL.",
    description: "AniList API предоставляет доступ к сотням тысяч тайтлов аниме и манги. Разработчики могут запрашивать рейтинги, даты выхода, трейлеры, списки персонажей, актеров озвучки (сэйю) и пользовательские рецензии с помощью гибких запросов GraphQL.",
    tags: ["movies", "anime", "manga", "graphql", "japan"],
    logo: "AA",
    websiteUrl: "https://anilist.co",
    documentationUrl: "https://anilist.gitbook.io/anilist-apiv2-docs/",
    githubUrl: "https://github.com/AniList",
    authentication: "None",
    format: "GraphQL",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "90 requests / min",
    rating: 4.9,
    ratingCount: 310,
    popularity: 2400,
    status: "active",
    features: ["Современный и мощный GraphQL интерфейс", "Исчерпывающая база аниме и манги", "Связи между сезонами, фильмами и спин-оффами", "Свободный доступ без обязательного ключа"]
  },
  {
    id: "kitsu-anime-api",
    name: "Kitsu API",
    category: "Movies",
    shortDescription: "Современный JSON:API для поиска аниме, манги, стриминговых сервисов и реакций зрителей.",
    description: "Kitsu предлагает элегантный интерфейс стандарта JSON:API для поиска анимационных фильмов, эпизодов, персонажей и трендов сообщества отаку по всему миру.",
    tags: ["movies", "anime", "kitsu", "jsonapi", "media"],
    logo: "KI",
    websiteUrl: "https://kitsu.io",
    documentationUrl: "https://kitsu.docs.apiary.io/",
    githubUrl: "https://github.com/hummingbird-me",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Разумное использование",
    rating: 4.7,
    ratingCount: 160,
    popularity: 1310,
    status: "active",
    features: ["Стандарт спецификации JSON:API", "Ссылки на официальный легальный просмотр", "Постеры и баннеры в отличном качестве", "Полнотекстовый поиск по жанрам"]
  },
  {
    id: "watchmode-api",
    name: "Watchmode Streaming API",
    category: "Movies",
    shortDescription: "Поиск провайдеров онлайн-просмотра: где легально посмотреть любой фильм (Netflix, Кинопоиск, Apple).",
    description: "Watchmode отслеживает каталоги сотен стриминговых сервисов в десятках стран мира. Позволяет мгновенно выяснить, где фильм доступен по подписке, в аренду или для бесплатного просмотра с рекламой.",
    tags: ["movies", "streaming", "netflix", "hbo", "where-to-watch"],
    logo: "WS",
    websiteUrl: "https://api.watchmode.com",
    documentationUrl: "https://api.watchmode.com/docs/",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "1,000 requests/month (Free)",
    rating: 4.7,
    ratingCount: 130,
    popularity: 1100,
    status: "active",
    features: ["Поддержка 200+ мировых стримингов", "Фильтрация по типу доступа (Subscription/Rent/Buy)", "Прямые диплинки на воспроизведение в приложении", "Региональная разбивка по странам"]
  },
  {
    id: "studio-ghibli-api",
    name: "Studio Ghibli API",
    category: "Movies",
    shortDescription: "Бесплатные ресурсы и данные обо всех анимационных шедеврах легендарной студии Хаяо Миядзаки.",
    description: "Открытый фанатский проект, каталогизирующий все классические полнометражные анимационные фильмы Studio Ghibli (Унесенные призраками, Мой сосед Тоторо, Ходячий замок). Содержит персонажей, локации и технику.",
    tags: ["movies", "ghibli", "miyazaki", "anime", "art"],
    logo: "SG",
    websiteUrl: "https://ghibliapi.vercel.app",
    documentationUrl: "https://ghibliapi.vercel.app/",
    githubUrl: "https://github.com",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Свободный доступ",
    rating: 4.9,
    ratingCount: 220,
    popularity: 1650,
    status: "active",
    features: ["Все анимационные шедевры Миядзаки", "Данные о персонажах и их видах", "Музыка и режиссеры картин", "Полностью открыт для учебных проектов"]
  },
  {
    id: "comic-vine-api",
    name: "Comic Vine API",
    category: "Movies",
    shortDescription: "Крупнейшая база комиксов, супергероев Marvel и DC, сюжетных арок и экранизаций.",
    description: "Comic Vine от Fandom содержит колоссальную базу знаний о вселенных комиксов, их выпусках, персонажах, создателях и связях с экранизациями в кино и сериалах.",
    tags: ["movies", "comics", "marvel", "dc", "superheroes"],
    logo: "CV",
    websiteUrl: "https://comicvine.gamespot.com",
    documentationUrl: "https://comicvine.gamespot.com/api/documentation",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "200 requests/hour",
    rating: 4.6,
    ratingCount: 110,
    popularity: 940,
    status: "active",
    features: ["Вселенные Marvel, DC, Dark Horse, Image", "Хронология сюжетных кроссоверов", "Профили супергероев и злодеев", "Архивы обложек выпусков"]
  },

  // ==========================================
  // 7. MUSIC & AUDIO +6
  // ==========================================
  {
    id: "genius-lyrics-api",
    name: "Genius Lyrics API",
    category: "Music",
    shortDescription: "Тексты песен, аннотации смыслов строк от артистов и метаданные музыкальных альбомов.",
    description: "Genius — крупнейшая в мире платформа текстов песен и аннотаций. API позволяет находить тексты любимых композиций, читать объяснения скрытых метафор от самих авторов и получать информацию о продюсерах.",
    tags: ["music", "lyrics", "genius", "rap", "annotation"],
    logo: "GL",
    websiteUrl: "https://genius.com",
    documentationUrl: "https://docs.genius.com",
    githubUrl: "https://github.com/genius",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Свободный доступ после регистрации",
    rating: 4.8,
    ratingCount: 290,
    popularity: 2350,
    status: "active",
    features: ["Официальные тексты песен сотен тысяч артистов", "Построчные аннотации смыслов строк", "Полнотекстовый поиск по фрагментам песни", "Информация о продюсерах и сэмплах"]
  },
  {
    id: "lastfm-api",
    name: "Last.fm Music API",
    category: "Music",
    shortDescription: "Музыкальные рекомендации, скробблинг прослушиваний, чарты похожих артистов и тегов.",
    description: "Last.fm API построен на многомиллиардной базе скробблов миллионов меломанов со всего мира. Сервис непревзойден в поиске похожих исполнителей (Similar Artists), биографиях музыкантов и глобальных тегах стилей.",
    tags: ["music", "lastfm", "scrobbling", "recommendations", "charts"],
    logo: "LM",
    websiteUrl: "https://www.last.fm",
    documentationUrl: "https://www.last.fm/api",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Свободный доступ с ключом",
    rating: 4.7,
    ratingCount: 260,
    popularity: 1980,
    status: "active",
    features: ["Умный подбор похожих исполнителей и треков", "Скробблинг истории прослушиваний", "Топ-чарты треков по странам", "Биографии групп и дискографии"]
  },
  {
    id: "musixmatch-api",
    name: "Musixmatch Lyrics API",
    category: "Music",
    shortDescription: "Синхронизированные построчные тексты песен (караоке-тайминги) для плееров и аудиосервисов.",
    description: "Musixmatch — главный поставщик синхронизированных текстов (Time-synced lyrics) для Spotify, Apple Music и Instagram. API позволяет отображать тексты песен с точностью до миллисекунды в такт звучанию музыки.",
    tags: ["music", "lyrics", "karaoke", "sync", "musixmatch"],
    logo: "ML",
    websiteUrl: "https://www.musixmatch.com",
    documentationUrl: "https://developer.musixmatch.com",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "2,000 calls/day (Free)",
    rating: 4.7,
    ratingCount: 180,
    popularity: 1450,
    status: "active",
    features: ["Синхронизация слов по миллисекундам (LRC)", "Переводы текстов песен на разные языки", "Каталог текстов для 100+ языков", "Официальные партнерские лицензии"]
  },
  {
    id: "radio-browser-api",
    name: "Radio Browser Community API",
    category: "Music",
    shortDescription: "Бесплатный каталог 40 000+ онлайн радиостанций со всего мира с прямыми MP3/AAC потоками.",
    description: "Radio Browser — это открытый проект сообщества, собирающий потоки интернет-радиостанций со всей планеты. API позволяет фильтровать станции по странам, жанрам, языкам вещания и качеству битрейта.",
    tags: ["music", "radio", "streaming", "audio", "opensource"],
    logo: "RB",
    websiteUrl: "https://www.radio-browser.info",
    documentationUrl: "https://de1.api.radio-browser.info/",
    githubUrl: "https://github.com/segler-alex/radio-browser",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Не ограничен",
    rating: 4.8,
    ratingCount: 210,
    popularity: 1650,
    status: "active",
    features: ["Более 40 000 радиостанций в каталоге", "Прямые URL аудиопотоков (AAC, MP3, OGG)", "Не требует регистрации и ключей доступа", "Поиск по жанрам, языкам и битрейту"]
  },
  {
    id: "listen-notes-podcast-api",
    name: "Listen Notes Podcast API",
    category: "Music",
    shortDescription: "Крупнейшая поисковая система подкастов: метаданные 3+ миллионов шоу и аудиодорожки выпусков.",
    description: "Listen Notes — это 'Google для подкастов'. API позволяет искать выпуски по ключевым фразам, находить новые шоу по жанрам, получать аудиофайлы выпусков и расшифровки разговоров.",
    tags: ["music", "podcasts", "audio", "shows", "listennotes"],
    logo: "LN",
    websiteUrl: "https://www.listennotes.com",
    documentationUrl: "https://www.listennotes.com/api/docs/",
    githubUrl: "https://github.com/ListenNotes",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "300 requests/month (Free)",
    rating: 4.7,
    ratingCount: 140,
    popularity: 1180,
    status: "active",
    features: ["База из 3 000 000+ подкастов со всего мира", "Прямые ссылки на аудиофайлы эпизодов", "Рекомендации похожих аудиопередач", "Полнотекстовый поиск по описаниям"]
  },
  {
    id: "jamendo-music-api",
    name: "Jamendo Music API",
    category: "Music",
    shortDescription: "Легальная бесплатная музыка по лицензии Creative Commons для видеороликов, игр и плееров.",
    description: "Jamendo предоставляет доступ к более чем 600 000 треков независимых авторов, распространяемых по лицензиям Creative Commons. Доступны прямые ссылки на скачивание аудиодорожек в формате MP3.",
    tags: ["music", "creative-commons", "royalty-free", "indie", "audio"],
    logo: "JM",
    websiteUrl: "https://www.jamendo.com",
    documentationUrl: "https://developer.jamendo.com/v3.0",
    githubUrl: "https://github.com/jamendo",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Свободный доступ для разработчиков",
    rating: 4.6,
    ratingCount: 120,
    popularity: 960,
    status: "active",
    features: ["600 000+ треков под лицензиями Creative Commons", "Прямой стриминг и скачивание в MP3", "Фильтрация по настроению и темпу музыки", "Идеально для фоновой музыки в играх"]
  },

  // ==========================================
  // 8. SOCIAL (Социальные сети и общение) +6
  // ==========================================
  {
    id: "slack-web-api",
    name: "Slack Web API",
    category: "Social",
    shortDescription: "Интеграция корпоративных чатов, создание ботов, отправка уведомлений и интерактивных блоков.",
    description: "Slack API открывает возможности для автоматизации рабочих процессов в командах. Позволяет отправлять сообщения с интерактивным дизайном Block Kit, управлять каналами, создавать ботов с ИИ и слушать события рабочего пространства.",
    tags: ["social", "slack", "chat", "workspace", "bots"],
    logo: "SW",
    websiteUrl: "https://slack.com",
    documentationUrl: "https://api.slack.com",
    githubUrl: "https://github.com/slackapi/node-slack-sdk",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "1 request / sec (Tier 1)",
    rating: 4.8,
    ratingCount: 380,
    popularity: 2800,
    status: "active",
    features: ["Интерактивный конструктор сообщений Block Kit", "Обработка событий через Events API", "Слеш-команды для мгновенных действий", "Официальный SDK Bolt для JS и Python"]
  },
  {
    id: "reddit-data-api",
    name: "Reddit Data API",
    category: "Social",
    shortDescription: "Чтение и публикация постов, тредов, комментариев и аналитика сабреддитов.",
    description: "Reddit API предоставляет доступ к крупнейшей социальной дискуссионной платформе планеты. Позволяет искать посты, парсить комментарии, отслеживать тренды сообществ и управлять учетными записями через OAuth2.",
    tags: ["social", "reddit", "communities", "discussions", "forum"],
    logo: "RD",
    websiteUrl: "https://www.reddit.com",
    documentationUrl: "https://www.reddit.com/dev/api/",
    githubUrl: "https://github.com/reddit",
    authentication: "OAuth 2.0",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "100 queries/min (OAuth)",
    rating: 4.6,
    ratingCount: 310,
    popularity: 2500,
    status: "active",
    features: ["Чтение горячих и топовых постов сабреддитов", "Древовидная структура комментариев", "Модерация сообществ через ботов", "Поиск по авторам и тегам"]
  },
  {
    id: "twilio-sms-api",
    name: "Twilio Communications API",
    category: "Social",
    shortDescription: "Отправка SMS-сообщений, совершение телефонных звонков и верификация номеров (2FA).",
    description: "Twilio — мировой лидер облачных коммуникаций. Позволяет отправлять транзакционные SMS в 180+ стран, создавать голосовых роботов (IVR), верифицировать пользователей по коду из SMS (Twilio Verify) и рассылать сообщения в WhatsApp.",
    tags: ["social", "sms", "telecom", "voice", "2fa"],
    logo: "TC",
    websiteUrl: "https://www.twilio.com",
    documentationUrl: "https://www.twilio.com/docs",
    githubUrl: "https://github.com/twilio/twilio-node",
    authentication: "Basic Auth",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "По квотам учетной записи",
    rating: 4.8,
    ratingCount: 410,
    popularity: 3200,
    status: "active",
    features: ["Доставка SMS по всему миру с высокой проходимостью", "Автоматические телефонные звонки с синтезом речи", "Готовый сервис двухфакторной аутентификации 2FA", "Интеграция с WhatsApp Business API"]
  },
  {
    id: "resend-email-api",
    name: "Resend Email API",
    category: "Social",
    shortDescription: "Современный API отправки транзакционных email-писем для разработчиков с поддержкой React Email.",
    description: "Resend совершил революцию в email-рассылках благодаря потрясающей скорости ответа, красивой документации и интеграции с React Email. Обеспечивает мгновенную доставку писем о сбросе пароля, подтверждении регистрации и чеков.",
    tags: ["social", "email", "resend", "transactional", "react-email"],
    logo: "RE",
    websiteUrl: "https://resend.com",
    documentationUrl: "https://resend.com/docs",
    githubUrl: "https://github.com/resend/resend-node",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "3,000 emails/month (Free)",
    rating: 4.9,
    ratingCount: 290,
    popularity: 2450,
    status: "active",
    features: ["3 000 бесплатных писем в месяц", "Верстка красивых шаблонов через React Email", "Мгновенные вебхуки о доставке и открытиях", "Отличная репутация IP для защиты от спама"]
  },
  {
    id: "mastodon-api",
    name: "Mastodon Decentralized API",
    category: "Social",
    shortDescription: "Открытый REST API децентрализованной федеративной сети микроблогов (Fediverse).",
    description: "Mastodon API позволяет взаимодействовать с федеративными серверами Fediverse. Поддерживает публикацию статусов, чтение глобальной и локальной ленты, подписки на пользователей любых независимых инстансов.",
    tags: ["social", "fediverse", "mastodon", "decentralized", "opensource"],
    logo: "MD",
    websiteUrl: "https://joinmastodon.org",
    documentationUrl: "https://docs.joinmastodon.org/client/intro/",
    githubUrl: "https://github.com/mastodon/mastodon",
    authentication: "OAuth 2.0",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "300 requests / 5 min",
    rating: 4.7,
    ratingCount: 160,
    popularity: 1380,
    status: "active",
    features: ["100% открытый исходный код и протокол", "Децентрализованная федеративная структура", "Потоковое вещание постов через WebSockets", "Свободен от алгоритмических манипуляций"]
  },
  {
    id: "pusher-channels-api",
    name: "Pusher Channels Realtime API",
    category: "Social",
    shortDescription: "Мгновенные WebSockets для создания онлайн-чатов, уведомлений и мультиплеерных механик.",
    description: "Pusher берет на себя управление сложной инфраструктурой постоянных вебсокет-соединений. Позволяет в несколько строк кода реализовать функционал печатающего собеседника, живые счетчики и индикаторы онлайн-статуса.",
    tags: ["social", "websockets", "realtime", "pusher", "chat"],
    logo: "PC",
    websiteUrl: "https://pusher.com",
    documentationUrl: "https://pusher.com/docs/channels/",
    githubUrl: "https://github.com/pusher",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "200,000 сообщений/день (Free)",
    rating: 4.8,
    ratingCount: 220,
    popularity: 1780,
    status: "active",
    features: ["200 000 сообщений в день бесплатно", "100 одновременных подключений в Free-плане", "Приватные и публичные каналы присутствия (Presence)", "Официальные библиотеки для веба и мобилок"]
  },

  // ==========================================
  // 9. NEWS (Новости и медиа) +6
  // ==========================================
  {
    id: "guardian-open-platform",
    name: "The Guardian Open Platform",
    category: "News",
    shortDescription: "Свободный доступ к архивам статей британского издания The Guardian с 1999 года по сей день.",
    description: "The Guardian Open Platform предоставляет полный текст статей, авторские колонки, теги, списки секций и галереи фото журналистов одного из авторитетнейших мировых изданий.",
    tags: ["news", "guardian", "journalism", "uk", "articles"],
    logo: "TG",
    websiteUrl: "https://open-platform.theguardian.com",
    documentationUrl: "https://open-platform.theguardian.com/documentation/",
    githubUrl: "https://github.com/guardian",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "5,000 requests/day (Developer)",
    rating: 4.8,
    ratingCount: 240,
    popularity: 1850,
    status: "active",
    features: ["Полные тексты более чем 2 000 000 статей", "Глубокий архив материалов с 1999 года", "Качественные фотографии журналистов", "5 000 бесплатных запросов ежедневно"]
  },
  {
    id: "currents-api",
    name: "Currents News API",
    category: "News",
    shortDescription: "Многоязычный поиск свежих новостей на 14 языках из тысяч независимых источников.",
    description: "Currents API собирает и анализирует новостные ленты со всего мира. Сервис поддерживает фильтрацию по странам, рубрикам и языкам, а также удаляет дублирующиеся материалы.",
    tags: ["news", "currents", "breaking", "multilingual", "feed"],
    logo: "CN",
    websiteUrl: "https://currentsapi.services",
    documentationUrl: "https://currentsapi.services/en/docs/",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "600 requests/day (Free)",
    rating: 4.6,
    ratingCount: 130,
    popularity: 1050,
    status: "active",
    features: ["Новости на 14 популярных мировых языках", "Умная дедупликация похожих сюжетов", "Уведомления о срочных событиях (Breaking News)", "Простая интеграция с JavaScript"]
  },
  {
    id: "gnews-api",
    name: "GNews API",
    category: "News",
    shortDescription: "Простой легковесный REST API для получения заголовков новостей Google News.",
    description: "GNews API собирает главные темы и актуальные сюжеты новостей по странам и ключевым словам, извлекая оригинальный текст, дату и ссылки на первоисточники.",
    tags: ["news", "gnews", "google-news", "headlines", "articles"],
    logo: "GN",
    websiteUrl: "https://gnews.io",
    documentationUrl: "https://gnews.io/docs/v4",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "100 requests/day (Free)",
    rating: 4.5,
    ratingCount: 150,
    popularity: 1190,
    status: "active",
    features: ["Быстрый парсинг топовых заголовков", "Фильтрация по географическим регионам", "Поиск статей по ключевым словам", "Возвращает чистый JSON с метаданными"]
  },
  {
    id: "spaceflight-news-api",
    name: "Spaceflight News API (SNAPI)",
    category: "News",
    shortDescription: "Открытый бесплатный API космических новостей, запусков ракет, миссий NASA и SpaceX.",
    description: "SNAPI агрегирует статьи и репортажи обо всех событиях космической отрасли от десятков специализированных изданий. Связан с каталогами запусков космических аппаратов.",
    tags: ["news", "space", "nasa", "spacex", "astronomy"],
    logo: "SN",
    websiteUrl: "https://spaceflightnewsapi.net",
    documentationUrl: "https://api.spaceflightnewsapi.net/v4/docs/",
    githubUrl: "https://github.com/TheSpaceDevs/spaceflightnewsapi",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Свободный публичный доступ",
    rating: 4.9,
    ratingCount: 180,
    popularity: 1420,
    status: "active",
    features: ["100% бесплатный и не требует ключей API", "Агрегация главных космических изданий", "Привязка статей к конкретным миссиям и ракетам", "Разработан сообществом The Space Devs"]
  },
  {
    id: "mediastack-api",
    name: "Mediastack News API",
    category: "News",
    shortDescription: "Глобальные живые новостные тренды из 7 500 изданий в 50 странах мира.",
    description: "Mediastack поставляет новостные ленты в формате JSON от ведущих медиахолдингов с задержкой не более пары минут после публикации.",
    tags: ["news", "mediastack", "media", "live", "global"],
    logo: "MN",
    websiteUrl: "https://mediastack.com",
    documentationUrl: "https://mediastack.com/documentation",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "500 requests/month (Free)",
    rating: 4.5,
    ratingCount: 95,
    popularity: 880,
    status: "active",
    features: ["Охват 50+ стран мира", "Категории: бизнес, спорт, технологии, наука", "Удобная фильтрация по датам публикаций", "Кеширование данных на CDN"]
  },
  {
    id: "associated-press-feed",
    name: "Associated Press Open Feeds",
    category: "News",
    shortDescription: "Официальные ленты агентства AP с проверенной журналистикой и мировыми событиями.",
    description: "Associated Press — старейшее информационное агентство мира, эталон фактчекинга и оперативных репортажей из горячих точек планеты.",
    tags: ["news", "ap", "press", "journalism", "investigation"],
    logo: "AP",
    websiteUrl: "https://apnews.com",
    documentationUrl: "https://developer.ap.org",
    githubUrl: "https://github.com",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: false,
    rateLimit: "По соглашению",
    rating: 4.8,
    ratingCount: 140,
    popularity: 1300,
    status: "active",
    features: ["Золотой стандарт мировой журналистики", "Прямые сводки с мест ключевых событий", "Глобальная сеть репортеров", "Высокая точность и объективность"]
  },

  // ==========================================
  // 10. DEVELOPMENT (Инструменты разработки) +6
  // ==========================================
  {
    id: "gitlab-api",
    name: "GitLab REST API",
    category: "Development",
    shortDescription: "Управление репозиториями, пайплайнами CI/CD, багами и деплоем в платформе GitLab.",
    description: "GitLab REST API позволяет автоматизировать полный цикл разработки программного обеспечения: создание веток, управление переменными CI/CD, триггеры пайплайнов, проверка качества кода и безопасность контейнеров.",
    tags: ["development", "gitlab", "cicd", "devops", "git"],
    logo: "GI",
    websiteUrl: "https://gitlab.com",
    documentationUrl: "https://docs.gitlab.com/ee/api/rest/",
    githubUrl: "https://gitlab.com/gitlab-org/gitlab",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "2,000 requests/min",
    rating: 4.8,
    ratingCount: 310,
    popularity: 2400,
    status: "active",
    features: ["Глубокая интеграция с GitLab CI/CD пайплайнами", "Управление приватными раннерами и контейнерами", "Полноценный аудит коммитов и код-ревью", "Поддержка Self-hosted серверов"]
  },
  {
    id: "docker-hub-api",
    name: "Docker Hub API",
    category: "Development",
    shortDescription: "Поиск контейнеров, тегов образов, статистики скачиваний и управление репозиториями Docker.",
    description: "Docker Hub API позволяет получать информацию об официальных образах контейнеров (Node, Python, Ubuntu, Postgres), скачивать манифесты слоев, проверять наличие уязвимостей и управлять вебхуками сборки.",
    tags: ["development", "docker", "containers", "devops", "hub"],
    logo: "DH",
    websiteUrl: "https://hub.docker.com",
    documentationUrl: "https://docs.docker.com/docker-hub/api/latest/",
    githubUrl: "https://github.com/docker",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "100 pull requests / 6 hours (Anon)",
    rating: 4.7,
    ratingCount: 290,
    popularity: 2250,
    status: "active",
    features: ["Поиск по миллионам публичных образов", "Информация о тегах, датах коммитов и размерах", "Вебхуки на автоматический пуш новых сборок", "Аутентификация через Personal Access Tokens"]
  },
  {
    id: "npm-registry-api",
    name: "NPM Registry API",
    category: "Development",
    shortDescription: "Бесплатный открытый доступ к метаданным 3+ миллионов JavaScript и Node.js пакетов.",
    description: "Официальный API реестра NPM (Node Package Manager). Позволяет программно узнавать количество еженедельных скачиваний пакетов, информацию о версиях, зависимостях package.json, лицензиях и авторах.",
    tags: ["development", "npm", "nodejs", "javascript", "packages"],
    logo: "NR",
    websiteUrl: "https://www.npmjs.com",
    documentationUrl: "https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md",
    githubUrl: "https://github.com/npm",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Свободный публичный доступ",
    rating: 4.9,
    ratingCount: 420,
    popularity: 3400,
    status: "active",
    features: ["100% бесплатный и не требует регистрации", "Статистика скачиваний за любой период времени", "Полное дерево зависимостей любого пакета", "История версий и релизные теги"]
  },
  {
    id: "vercel-api",
    name: "Vercel API",
    category: "Development",
    shortDescription: "Управление деплоем фронтенд-проектов, бессерверными функциями, DNS и доменами.",
    description: "Vercel API позволяет автоматизировать развертывание современных веб-приложений (Next.js, Vite, Astro). Позволяет запускать сборки, настраивать переменные окружения, проверять логи серверов и управлять доменами.",
    tags: ["development", "vercel", "nextjs", "serverless", "deployment"],
    logo: "VE",
    websiteUrl: "https://vercel.com",
    documentationUrl: "https://vercel.com/docs/rest-api",
    githubUrl: "https://github.com/vercel",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "В рамках квот аккаунта",
    rating: 4.8,
    ratingCount: 350,
    popularity: 2700,
    status: "active",
    features: ["Программный триггер деплоев из кода", "Управление DNS записями и SSL-сертификатами", "Просмотр логов рантайма в реальном времени", "Мгновенные предпросмотровые ссылки (Previews)"]
  },
  {
    id: "postman-api",
    name: "Postman API",
    category: "Development",
    shortDescription: "Программное управление коллекциями запросов, мок-серверами и мониторингом API.",
    description: "Postman API дает возможность синхронизировать коллекции тестов API, запускать автоматизированные прогоны проверок в CI/CD, генерировать мок-серверы и экспортировать документацию OpenAPI.",
    tags: ["development", "postman", "testing", "openapi", "mock"],
    logo: "PO",
    websiteUrl: "https://www.postman.com",
    documentationUrl: "https://learning.postman.com/docs/developer/postman-api/intro-api/",
    githubUrl: "https://github.com/postmanlabs",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "По тарифу аккаунта",
    rating: 4.7,
    ratingCount: 280,
    popularity: 2100,
    status: "active",
    features: ["Управление коллекциями тестовых сценариев", "Автоматический запуск мониторинга работоспособности", "Синхронизация схем OpenAPI и Swagger", "Создание облачных Mock-серверов"]
  },
  {
    id: "cloudflare-api",
    name: "Cloudflare API",
    category: "Development",
    shortDescription: "Управление DNS-серверами, защитой от DDoS-атак, CDN-кешированием и воркерами (Workers).",
    description: "Cloudflare API позволяет разработчикам полностью автоматизировать настройку безопасности и доставки веб-ресурсов: сброс кеша CDN, редактирование DNS-записей, настройка правил WAF и деплой кода в Cloudflare Workers.",
    tags: ["development", "cloudflare", "dns", "cdn", "security"],
    logo: "CL",
    websiteUrl: "https://www.cloudflare.com",
    documentationUrl: "https://developers.cloudflare.com/api/",
    githubUrl: "https://github.com/cloudflare",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "1,200 requests / 5 min",
    rating: 4.9,
    ratingCount: 460,
    popularity: 3500,
    status: "active",
    features: ["Мгновенная очистка кеша CDN одной командой", "Управление DNS зонами с поддержкой Anycast", "Запуск бессерверных функций Cloudflare Workers", "Настройка правил файрвола и защиты от ботов"]
  },

  // ==========================================
  // 11. E-COMMERCE (Электронная коммерция) +6
  // ==========================================
  {
    id: "woocommerce-rest-api",
    name: "WooCommerce REST API",
    category: "E-commerce",
    shortDescription: "Управление товарами, заказами, клиентами и купонами на базе платформы WordPress/WooCommerce.",
    description: "WooCommerce REST API позволяет интегрировать популярнейшую систему онлайн-торговли на базе WordPress с любыми сторонними мобильными приложениями, CRM и складскими системами 1C/МойСклад.",
    tags: ["ecommerce", "woocommerce", "wordpress", "shop", "orders"],
    logo: "WO",
    websiteUrl: "https://woocommerce.com",
    documentationUrl: "https://woocommerce.github.io/woocommerce-rest-api-docs/",
    githubUrl: "https://github.com/woocommerce/woocommerce",
    authentication: "Basic Auth",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Ограничивается вашим хостингом",
    rating: 4.7,
    ratingCount: 340,
    popularity: 2800,
    status: "active",
    features: ["Полный CRUD для каталога товаров и категорий", "Уведомления через вебхуки о новых заказах", "Синхронизация остатков на складах", "Управление скидочными купонами и налогами"]
  },
  {
    id: "square-developer-api",
    name: "Square Payments & Catalog API",
    category: "E-commerce",
    shortDescription: "Прием платежей в офлайн-магазинах (POS терминалы) и онлайн-эквайринг, управление инвентарем.",
    description: "Square API связывает онлайн-продажи и реальные торговые точки. Позволяет синхронизировать складские запасы товаров, принимать банковские карты через POS-терминалы и организовывать интернет-магазины с единой базой клиентов.",
    tags: ["ecommerce", "square", "pos", "retail", "payments"],
    logo: "SP",
    websiteUrl: "https://squareup.com",
    documentationUrl: "https://developer.squareup.com/docs",
    githubUrl: "https://github.com/square",
    authentication: "OAuth 2.0",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Свободный тестовый Sandbox",
    rating: 4.8,
    ratingCount: 220,
    popularity: 1890,
    status: "active",
    features: ["Единый инвентарь для интернет-магазина и кассы в зале", "Прием Apple Pay, Google Pay и пластиковых карт", "Управление программами лояльности покупателей", "Тестовая среда Sandbox для разработчиков"]
  },
  {
    id: "printful-api",
    name: "Printful Print-on-Demand API",
    category: "E-commerce",
    shortDescription: "Печать принтов на одежде и сувенирах по требованию с автоматической доставкой покупателю.",
    description: "Printful API позволяет запускать мерч-магазины без собственных складов и оборудования. Как только в вашем приложении оформляется заказ, API передает макет принта на фабрику Printful, где товар печатают и отправляют клиенту с вашим брендом.",
    tags: ["ecommerce", "merch", "printful", "dropshipping", "apparel"],
    logo: "PP",
    websiteUrl: "https://www.printful.com",
    documentationUrl: "https://developers.printful.com/docs/",
    githubUrl: "https://github.com",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "120 requests/min",
    rating: 4.7,
    ratingCount: 165,
    popularity: 1350,
    status: "active",
    features: ["Генерация фотореалистичных мокапов футболок и кружек", "Автоматический расчет стоимости доставки по миру", "Белая маркировка (White-label брендирование)", "Отслеживание статусов посылок через трек-номера"]
  },
  {
    id: "snipcart-api",
    name: "Snipcart API",
    category: "E-commerce",
    shortDescription: "Добавление корзины покупок и чекаута на любой статический HTML/Jamstack сайт за 5 минут.",
    description: "Snipcart позволяет превратить любой статический сайт в полноценный интернет-магазин добавлением пары HTML-атрибутов. API предоставляет вебхуки для валидации заказов, управления доставкой и синхронизации с базой данных.",
    tags: ["ecommerce", "snipcart", "jamstack", "cart", "static"],
    logo: "SN",
    websiteUrl: "https://snipcart.com",
    documentationUrl: "https://docs.snipcart.com/v3",
    githubUrl: "https://github.com/snipcart",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Бесплатный тестовый режим навсегда",
    rating: 4.8,
    ratingCount: 140,
    popularity: 1190,
    status: "active",
    features: ["Работает на статическом HTML без бэкенда", "Настраиваемый стиль корзины под дизайн сайта", "Поддержка цифровых товаров и скачиваний", "Интеграция с десятками платежных шлюзов"]
  },
  {
    id: "gumroad-api",
    name: "Gumroad API",
    category: "E-commerce",
    shortDescription: "Продажа цифровых товаров, курсов, книг и софта с генерацией лицензионных ключей.",
    description: "Gumroad API позволяет авторам контента и независимым разработчикам продавать цифровые продукты (электронные книги, шаблоны, плагины). API умеет генерировать лицензионные ключи, проверять валидность подписок и слать уведомления о покупках (Ping).",
    tags: ["ecommerce", "gumroad", "digital", "creators", "licenses"],
    logo: "GU",
    websiteUrl: "https://gumroad.com",
    documentationUrl: "https://app.gumroad.com/api",
    githubUrl: "https://github.com",
    authentication: "OAuth 2.0",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Свободный доступ с аккаунтом",
    rating: 4.6,
    ratingCount: 155,
    popularity: 1280,
    status: "active",
    features: ["Генерация и проверка лицензионных ключей софта", "Продажа цифровых файлов без настройки хостинга", "Вебхуки Ping на факт совершения оплаты", "Управление скидочными промокодами"]
  },
  {
    id: "paddle-billing-api",
    name: "Paddle Billing API",
    category: "E-commerce",
    shortDescription: "Merchant of Record для продажи SaaS по всему миру с автоматическим расчетом налогов (НДС/Sales Tax).",
    description: "Paddle выступает в роли Торгового Посредника (Merchant of Record). Сервис берет на себя все бремя налогового законодательства в 200+ странах мира, обеспечивая прием платежей за подписочные B2B и B2C SaaS-сервисы.",
    tags: ["ecommerce", "paddle", "saas", "subscriptions", "taxes"],
    logo: "PB",
    websiteUrl: "https://www.paddle.com",
    documentationUrl: "https://developer.paddle.com/api-reference/overview",
    githubUrl: "https://github.com/PaddleHQ",
    authentication: "Bearer Token",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Песочница Sandbox для тестов",
    rating: 4.8,
    ratingCount: 170,
    popularity: 1420,
    status: "active",
    features: ["Автоматический расчет и уплата налогов в 200+ юрисдикциях", "Управление подписками, апгрейдами и отменами", "Встроенная защита от чарджбэков", "Интеграция через Paddle.js на фронтенде"]
  },

  // ==========================================
  // 12. OTHER (Медиа, утилиты и прочее) +6
  // ==========================================
  {
    id: "pexels-api",
    name: "Pexels Photo & Video API",
    category: "Other",
    shortDescription: "Миллионы бесплатных стоковых фотографий и видеороликов высокого разрешения 4K.",
    description: "Pexels API предоставляет разработчикам полный доступ к библиотеке бесплатных медиаресурсов. Позволяет искать видео и фото по ключевым словам, ориентации, цвету и автоматически адаптировать контент под нужные разрешения экранов.",
    tags: ["other", "photos", "videos", "media", "stock"],
    logo: "PP",
    websiteUrl: "https://www.pexels.com",
    documentationUrl: "https://www.pexels.com/api/documentation/",
    githubUrl: "https://github.com/pexels",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "20,000 requests/month (Free)",
    rating: 4.9,
    ratingCount: 260,
    popularity: 2150,
    status: "active",
    features: ["Бесплатные видеоролики в разрешении Full HD и 4K", "Миллионы фотографий со свободной лицензией", "Поиск по преобладающему оттенку цвета", "20 000 бесплатных запросов каждый месяц"]
  },
  {
    id: "cloudinary-api",
    name: "Cloudinary Media API",
    category: "Other",
    shortDescription: "Трансформация, сжатие, распознавание лиц и CDN-доставка картинок и видео по URL параметрам.",
    description: "Cloudinary — индустриальный стандарт облачного медиа-менеджмента. Позволяет изменять размер, обрезать фото по лицам, конвертировать изображения в WebP/AVIF и накладывать водяные знаки, просто изменяя параметры в URL ссылке.",
    tags: ["other", "images", "cdn", "video", "optimization"],
    logo: "CM",
    websiteUrl: "https://cloudinary.com",
    documentationUrl: "https://cloudinary.com/documentation",
    githubUrl: "https://github.com/cloudinary/cloudinary_js",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "25 кредитов в месяц (Free)",
    rating: 4.8,
    ratingCount: 310,
    popularity: 2650,
    status: "active",
    features: ["Умная обрезка с фокусом на лицах людей", "Автоматический выбор наилучшего формата (WebP/AVIF)", "Оптимизация скорости загрузки сайтов (Core Web Vitals)", "Глобальная сеть быстрой доставки CDN"]
  },
  {
    id: "nasa-open-apis",
    name: "NASA Open APIs",
    category: "Other",
    shortDescription: "Астрономическая картина дня (APOD), снимки марсоходов Curiosity и данные астероидов.",
    description: "Официальный портал открытых данных аэрокосмического агентства NASA. Включает APOD (Astronomy Picture of the Day), фотографии с камер марсоходов на Марсе, трекинг сближающихся с Землей астероидов (NeoWs) и звуки космоса.",
    tags: ["other", "nasa", "space", "mars", "astronomy"],
    logo: "NO",
    websiteUrl: "https://api.nasa.gov",
    documentationUrl: "https://api.nasa.gov/",
    githubUrl: "https://github.com/nasa",
    authentication: "API Key",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "1,000 requests/hour (Free)",
    rating: 4.9,
    ratingCount: 380,
    popularity: 3100,
    status: "active",
    features: ["Ежедневное фото космоса APOD с описанием астрофизиков", "Реальные фотоснимки с марсоходов Curiosity и Perseverance", "Мониторинг потенциально опасных астероидов", "100% бесплатно для учебных и научных проектов"]
  },
  {
    id: "wikipedia-rest-api",
    name: "Wikimedia REST API",
    category: "Other",
    shortDescription: "Официальный REST API для чтения статей Википедии, кратких выжимок, превью и фактов дня.",
    description: "Wikimedia REST API предоставляет структурированный доступ к величайшей энциклопедии человечества на 300+ языках мира. Позволяет получать краткие карточки статей для всплывающих подсказок, полные тексты и статистику просмотров страниц.",
    tags: ["other", "wikipedia", "encyclopedia", "knowledge", "free"],
    logo: "WI",
    websiteUrl: "https://www.wikimedia.org",
    documentationUrl: "https://en.wikipedia.org/api/rest_v1/",
    githubUrl: "https://github.com/wikimedia",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "До 200 запросов/сек при указании User-Agent",
    rating: 4.9,
    ratingCount: 350,
    popularity: 2950,
    status: "active",
    features: ["Краткие выжимки статей для быстрых карточек (Pageviews)", "Поддержка более 300 мировых языков", "Случайные статьи и подборки 'В этот день'", "Не требует ключей и абсолютно бесплатен"]
  },
  {
    id: "random-user-generator",
    name: "Random User Generator",
    category: "Other",
    shortDescription: "Генератор реалистичных случайных профилей пользователей (фото, имена, адреса, телефоны).",
    description: "RandomUser.me — легендарный инструмент веб-разработчиков для наполнения макетов и прототипов реалистичными данными. Возвращает аватары людей, полные имена, реалистичные email, номера телефонов, координаты и логины.",
    tags: ["other", "mock", "users", "testing", "placeholders"],
    logo: "RU",
    websiteUrl: "https://randomuser.me",
    documentationUrl: "https://randomuser.me/documentation",
    githubUrl: "https://github.com/RandomAPI/Randomuser.me-Node",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Практически не ограничен",
    rating: 4.9,
    ratingCount: 410,
    popularity: 3300,
    status: "active",
    features: ["Реалистичные портретные фотографии людей", "Фильтрация по национальностям и полу", "Поддержка генерации списков до 5 000 пользователей", "Идеальный инструмент для верстки списков и таблиц"]
  },
  {
    id: "public-holidays-api",
    name: "Nager.Date Public Holidays API",
    category: "Other",
    shortDescription: "Календарь официальных государственных и национальных праздников для 100+ стран мира.",
    description: "Nager.Date предоставляет точные даты государственных выходных и праздничных дней для более чем 100 стран планеты. Помогает планировать графики доставок, рабочие календари и бронирования.",
    tags: ["other", "holidays", "calendar", "dates", "countries"],
    logo: "NP",
    websiteUrl: "https://date.nager.at",
    documentationUrl: "https://date.nager.at/Api",
    githubUrl: "https://github.com/nager/Nager.Date",
    authentication: "None",
    format: "JSON",
    https: true,
    cors: true,
    freeTier: true,
    rateLimit: "Свободный доступ",
    rating: 4.7,
    ratingCount: 140,
    popularity: 1120,
    status: "active",
    features: ["Государственные праздники более чем 100 стран", "Учет региональных праздников внутри федераций", "Проверка, является ли конкретный день рабочим", "Не требует ключей авторизации"]
  }
];

function generateSearchKeywords(name, shortDescription, category, tags = []) {
  const combined = `${name || ""} ${shortDescription || ""} ${category || ""} ${(tags || []).join(" ")}`.toLowerCase();
  const words = combined
    .replace(/[^\w\sа-яё]/gi, " ")
    .split(/\s+/)
    .filter((w) => w.length >= 2);
  return Array.from(new Set(words));
}

function toFirestoreFields(obj) {
  const fields = {};
  for (const [key, val] of Object.entries(obj)) {
    if (key === "id") continue;
    if (typeof val === "string") {
      fields[key] = { stringValue: val };
    } else if (typeof val === "number") {
      fields[key] = Number.isInteger(val)
        ? { integerValue: String(val) }
        : { doubleValue: val };
    } else if (typeof val === "boolean") {
      fields[key] = { booleanValue: val };
    } else if (Array.isArray(val)) {
      fields[key] = {
        arrayValue: {
          values: val.map((v) => ({ stringValue: String(v) }))
        }
      };
    }
  }
  return { fields };
}

async function uploadApi(api) {
  const name = api.name.trim();
  const searchKeywords = generateSearchKeywords(
    name,
    api.shortDescription,
    api.category,
    api.tags
  );

  const docData = {
    ...api,
    name,
    nameLower: name.toLowerCase(),
    slug: api.id,
    searchKeywords,
    status: api.status || "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };

  const payload = toFirestoreFields(docData);
  const url = `https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents/apis/${api.id}`;

  const res = await fetch(url, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload)
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`HTTP ${res.status}: ${errText}`);
  }

  return await res.json();
}

async function run() {
  console.log("==================================================");
  console.log(`Запуск массовой загрузки еще ${ADDITIONAL_APIS.length} API...`);
  console.log(`Проект Firestore: ${PROJECT_ID}`);
  console.log("==================================================");

  let success = 0;
  let errors = 0;

  for (let i = 0; i < ADDITIONAL_APIS.length; i++) {
    const api = ADDITIONAL_APIS[i];
    try {
      await uploadApi(api);
      success++;
      console.log(`[${i + 1}/${ADDITIONAL_APIS.length}]  Загружен: ${api.name} (${api.category})`);
    } catch (err) {
      errors++;
      console.error(`[${i + 1}/${ADDITIONAL_APIS.length}]  Ошибка ${api.name}:`, err.message);
    }
    await new Promise((r) => setTimeout(r, 70));
  }

  console.log("==================================================");
  console.log(` Загрузка завершена! Успешно добавлено: ${success}, Ошибок: ${errors}`);
  console.log("==================================================");

  // Combine and update demoData.js
  const combined = [...INITIAL_APIS, ...ADDITIONAL_APIS];
  const content = `/**
 * API Library - demoData.js
 * Comprehensive Collection of 100+ Curated Developer APIs across all 12 Categories
 */

export const DEMO_APIS = ${JSON.stringify(combined, null, 2)};
`;
  fs.writeFileSync("js/demoData.js", content, "utf8");
  console.log(` Файл js/demoData.js успешно обновлен, суммарно теперь: ${combined.length} API!`);
}

run();
